import { Chain, WalletChain, WalletOption } from "@swapkit/helpers";
import { PHANTOM_SUPPORTED_CHAINS } from "@swapkit/wallet-phantom";

export const AllChains = [
    Chain.Arbitrum,
    Chain.Avalanche,
    Chain.Base,
    Chain.BinanceSmartChain,
    Chain.Bitcoin,
    Chain.BitcoinCash,
    Chain.Cosmos,
    Chain.Dash,
    Chain.Dogecoin,
    Chain.Ethereum,
    Chain.Litecoin,
    Chain.Optimism,
    Chain.Polygon,
    Chain.Polkadot,
    Chain.Maya,
    Chain.Kujira,
    Chain.THORChain,
    Chain.Solana,
] as Chain[];

export const availableChainsByWallet: { [key in WalletOption]: Chain[] } = {
    [WalletOption.BRAVE]: AllChains,
    [WalletOption.COINBASE_MOBILE]: AllChains,
    [WalletOption.COINBASE_WEB]: AllChains,
    [WalletOption.EIP6963]: AllChains,
    [WalletOption.KEPLR]: [Chain.Cosmos, Chain.Kujira],
    [WalletOption.LEAP]: [Chain.Cosmos, Chain.Kujira],
    [WalletOption.LEDGER]: AllChains,
    [WalletOption.METAMASK]: AllChains,
    [WalletOption.OKX_MOBILE]: AllChains,
    [WalletOption.PHANTOM]: PHANTOM_SUPPORTED_CHAINS,
    [WalletOption.POLKADOT_JS]: [Chain.Polkadot],
    [WalletOption.TRUSTWALLET_WEB]: AllChains,
    [WalletOption.XDEFI]: AllChains,
    [WalletOption.KEYSTORE]: [...AllChains, Chain.Polkadot],
    [WalletOption.KEEPKEY]: [
        Chain.Arbitrum,
        Chain.Avalanche,
        Chain.BinanceSmartChain,
        Chain.Bitcoin,
        Chain.BitcoinCash,
        Chain.Cosmos,
        Chain.Dash,
        Chain.Dogecoin,
        Chain.Ethereum,
        Chain.Litecoin,
        Chain.Optimism,
        Chain.Polygon,
        Chain.THORChain,
        Chain.Maya,
    ],
    [WalletOption.KEEPKEY_BEX]: [
        Chain.Arbitrum,
        Chain.Avalanche,
        Chain.BinanceSmartChain,
        Chain.Bitcoin,
        Chain.BitcoinCash,
        Chain.Base,
        Chain.Cosmos,
        Chain.Dash,
        Chain.Dogecoin,
        Chain.Ethereum,
        Chain.Litecoin,
        Chain.Optimism,
        Chain.Polygon,
        Chain.THORChain,
        Chain.Maya,
    ],
    [WalletOption.TREZOR]: [
        Chain.Base,
        Chain.Bitcoin,
        Chain.BitcoinCash,
        Chain.Litecoin,
        Chain.Dash,
        Chain.Dogecoin,
        Chain.Ethereum,
        Chain.Avalanche,
        Chain.BinanceSmartChain,
        Chain.Optimism,
        Chain.Arbitrum,
        Chain.Polygon,
    ],
    [WalletOption.WALLETCONNECT]: [
        Chain.Ethereum,
        Chain.Base,
        Chain.BinanceSmartChain,
        Chain.Avalanche,
        Chain.THORChain,
        Chain.Maya,
        Chain.Polygon,
        Chain.Arbitrum,
        Chain.Optimism,
    ],
    [WalletOption.OKX]: [
        Chain.Ethereum,
        Chain.Avalanche,
        Chain.Base,
        Chain.BinanceSmartChain,
        Chain.Bitcoin,
        Chain.Cosmos,
        Chain.Polygon,
        Chain.Arbitrum,
        Chain.Optimism,
    ],
    [WalletOption.TALISMAN]: [
        Chain.Ethereum,
        Chain.Base,
        Chain.Arbitrum,
        Chain.Avalanche,
        Chain.Polygon,
        Chain.BinanceSmartChain,
        Chain.Optimism,
        Chain.Polkadot,
    ],
    [WalletOption.EXODUS]: [
        Chain.Ethereum,
        Chain.BinanceSmartChain,
        Chain.Polygon,
        Chain.Bitcoin,
    ],
    [WalletOption.LEDGER_LIVE]: [],
    [WalletOption.RADIX_WALLET]: [Chain.Radix],
};
